name = "it-toolbox"
# 必须设置为 pages
pages = true 

# 定义与 Cloudflare 兼容的日期
compatibility_date = "2024-11-01"
# 启用最新的功能特性
compatibility_flags = ["nodejs_compat"]

[build]
# 如果你的构建流程在 package.json 中，通常不需要在这里写 build_command
# Cloudflare 会自动执行你在控制台设置的 Build Command
# 但建议确保你的函数所在目录被正确识别
